apiVersion: apps/v1
kind: Deployment
metadata:
 name: the-deployment
 labels:
   deployment: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: demo
    spec:
      containers:
      - name: the-container
        image: docker.io/halilkarimis/argo-test:0.1.9
        ports:
        - containerPort: 5000
        imagePullPolicy: Always